{
 "title": "Vehicle Location",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Current Location",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select latitude, longitude from vehicle_location_data where vin=(select vin from vehicle_location_data limit 1) order by id desc limit 1;"
    }
   ]
  },
  {
   "title": "Vehicle Locations",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select * from vehicle_location_data where vin=(select vin from vehicle_location_data limit 1) and timestamp between $__timeFrom()  and $__timeTo();"
    }
   ]
  },
  {
   "title": "Vehicle Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\nclientid,\nevent,\ncreated_at\nFROM vehicle_events ORDER BY id desc LIMIT 10;"
    }
   ]
  }
 ]
}