CREATE TABLE IF NOT EXISTS vehicle_events (
id SERIAL  PRIMARY KEY,
clientid VARCHAR(255),
event VARCHAR(255),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS vehicle_location_data (
id SERIAL  PRIMARY KEY,
vin VARCHAR(17),
latitude FLOAT NOT NULL,
longitude FLOAT NOT NULL,
timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

